dungeons = [

    # Dungeon 1
    [
        ['Dungeon Entrance', 'Strange Room',      'Red Room',         'Mythical Shop'],
        ['Room of Webs',     'Mythical Shop',     'Boney Room',       'Strange Room'],
        ['Smoldering Room',  'Suspicious Room',   'Ominous Room',     'Compelling Room'],
        ['Strange Room',     'Echoing Room',      'Watchful Room',    'Mythical Shop'],
        ['Sulfurous Room',   'Splintered Room',   'Strange Room',     'Compelling Room'],
        ['Suspicious Room',  'Stale Room',        'Red Room',         'Strange Room'],
        ['Ominous Room',     'Strange Room',      'Compelling Room',  'Strange Room'],
        ['Howling Room',     'Room of Webs',      'Smoldering Room',  'Mythical Shop'],
        ['Crawling Room',    'Watchful Room',     'Echoing Room',     'Compelling Room'],
        ['Whispering Room',  'Sulfurous Room',    'Strange Room',     'Splintered Room'],
        ['Red Room',         'Stale Room',        'Strange Room',     'Suspicious Room'],
        ['Boney Room',       'Crawling Room',     'Whispering Room',  'Howling Room'],
        ['Room of Webs',     'Smoldering Room',   'Ominous Room',     'Strange Room'],
        ['Mythical Shop',    'Sulfurous Room',    'Echoing Room',     'Strange Room'],
        ['Strange Room',     'Dungeon Exit',      'Splintered Room',  'Compelling Room'],
    ],

    # Dungeon 2
    [
        ['Dungeon Entrance', 'Strange Room',      'Boney Room',       'Mythical Shop'],
        ['Howling Room',     'Compelling Room',   'Strange Room',     'Compelling Room'],
        ['Room of Webs',     'Mythical Shop',     'Suspicious Room',  'Strange Room'],
        ['Ominous Room',     'Crawling Room',     'Compelling Room',  'Watchful Room'],
        ['Smoldering Room',  'Strange Room',      'Splintered Room',  'Strange Room'],
        ['Compelling Room',  'Sulfurous Room',    'Echoing Room',     'Strange Room'],
        ['Red Room',         'Strange Room',      'Whispering Room',  'Mythical Shop'],
        ['Room of Webs',     'Howling Room',      'Ominous Room',     'Boney Room'],
        ['Strange Room',     'Suspicious Room',   'Compelling Room',  'Crawling Room'],
        ['Stale Room',       'Red Room',          'Sulfurous Room',   'Watchful Room'],
        ['Smoldering Room',  'Strange Room',      'Compelling Room',  'Strange Room'],
        ['Echoing Room',     'Splintered Room',   'Whispering Room',  'Mythical Shop'],
        ['Crawling Room',    'Strange Room',      'Room of Webs',     'Ominous Room'],
        ['Howling Room',     'Stale Room',        'Compelling Room',  'Sulfurous Room'],
        ['Mythical Shop',    'Compelling Room',   'Echoing Room',     'Dungeon Exit'],
    ],

    # Dungeon 3
    [
        ['Dungeon Entrance', 'Strange Room',      'Watchful Room',    'Mythical Shop'],
        ['Boney Room',       'Ominous Room',      'Strange Room',     'Compelling Room'],
        ['Suspicious Room',  'Strange Room',      'Whispering Room',  'Mythical Shop'],
        ['Smoldering Room',  'Red Room',          'Strange Room',     'Strange Room'],
        ['Stale Room',       'Room of Webs',      'Compelling Room',  'Strange Room'],
        ['Crawling Room',    'Howling Room',      'Strange Room',     'Compelling Room'],
        ['Splintered Room',  'Mythical Shop',     'Suspicious Room',  'Boney Room'],
        ['Ominous Room',     'Room of Webs',      'Compelling Room',  'Echoing Room'],
        ['Red Room',         'Compelling Room',   'Strange Room',     'Whispering Room'],
        ['Watchful Room',    'Stale Room',        'Howling Room',     'Strange Room'],
        ['Crawling Room',    'Smoldering Room',   'Sulfurous Room',   'Compelling Room'],
        ['Room of Webs',     'Strange Room',      'Red Room',         'Stale Room'],
        ['Ominous Room',     'Mythical Shop',     'Splintered Room',  'Whispering Room'],
        ['Echoing Room',     'Strange Room',      'Compelling Room',  'Sulfurous Room'],
        ['Strange Room',     'Dungeon Exit',      'Mythical Shop',    'Compelling Room'],
    ],

    # Dungeon 4
    [
        ['Dungeon Entrance', 'Strange Room',      'Red Room',         'Mythical Shop'],
        ['Watchful Room',    'Compelling Room',   'Smoldering Room',  'Strange Room'],
        ['Suspicious Room',  'Room of Webs',      'Strange Room',     'Mythical Shop'],
        ['Stale Room',       'Sulfurous Room',    'Compelling Room',  'Strange Room'],
        ['Ominous Room',     'Red Room',          'Strange Room',     'Crawling Room'],
        ['Echoing Room',     'Strange Room',      'Splintered Room',  'Whispering Room'],
        ['Howling Room',     'Compelling Room',   'Strange Room',     'Room of Webs'],
        ['Strange Room',     'Strange Room',      'Boney Room',       'Suspicious Room'],
        ['Mythical Shop',    'Compelling Room',   'Strange Room',     'Stale Room'],
        ['Smoldering Room',  'Howling Room',      'Echoing Room',     'Strange Room'],
        ['Whispering Room',  'Strange Room',      'Sulfurous Room',   'Strange Room'],
        ['Room of Webs',     'Splintered Room',   'Red Room',         'Compelling Room'],
        ['Crawling Room',    'Ominous Room',      'Strange Room',     'Stale Room'],
        ['Strange Room',     'Boney Room',        'Compelling Room',  'Mythical Shop'],
        ['Compelling Room',  'Smoldering Room',   'Dungeon Exit',     'Echoing Room'],
    ],

    # Dungeon 5
    [
        ['Dungeon Entrance', 'Strange Room',      'Strange Room',     'Mythical Shop'],
        ['Room of Webs',     'Whispering Room',   'Stale Room',       'Strange Room'],
        ['Sulfurous Room',   'Suspicious Room',   'Ominous Room',     'Red Room'],
        ['Howling Room',     'Strange Room',      'Strange Room',     'Compelling Room'],
        ['Crawling Room',    'Room of Webs',      'Boney Room',       'Smoldering Room'],
        ['Mythical Shop',    'Watchful Room',     'Strange Room',     'Compelling Room'],
        ['Stale Room',       'Splintered Room',   'Red Room',         'Strange Room'],
        ['Whispering Room',  'Compelling Room',   'Strange Room',     'Strange Room'],
        ['Smoldering Room',  'Strange Room',      'Crawling Room',    'Watchful Room'],
        ['Ominous Room',     'Compelling Room',   'Room of Webs',     'Mythical Shop'],
        ['Strange Room',     'Suspicious Room',   'Echoing Room',     'Compelling Room'],
        ['Splintered Room',  'Strange Room',      'Strange Room',     'Sulfurous Room'],
        ['Red Room',         'Stale Room',        'Compelling Room',  'Whispering Room'],
        ['Mythical Shop',    'Strange Room',      'Smoldering Room',  'Boney Room'],
        ['Compelling Room',  'Dungeon Exit',      'Mythical Shop',    'Ominous Room'],
    ]
]
